/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Notification
 #	author : miyako
 #	2016/08/01
 #
 # --------------------------------------------------------------------------------*/



// --- Notification
void Notification_SET_METHOD(sLONG_PTR *pResult, PackagePtr pParams);
void Notification_Get_method(sLONG_PTR *pResult, PackagePtr pParams);
void Notification_ADD_OBSERVER(sLONG_PTR *pResult, PackagePtr pParams);
void Notification_REMOVE_OBSERVER(sLONG_PTR *pResult, PackagePtr pParams);
void Notification_POST(sLONG_PTR *pResult, PackagePtr pParams);

typedef PA_long32 process_number_t;
typedef PA_long32 process_stack_size_t;
typedef PA_long32 method_id_t;
typedef PA_Unichar* process_name_t;

void listenerLoop(void);
void listenerLoopStart(void);
void listenerLoopFinish(void);
void listenerLoopExecute(void);